### PR TITLE
Integrate on OS matrix

### PR DESCRIPTION
**Pull request by aledeniz**
Add the strategy to build and test in parallel also on MacOs.

### CODE REVIEW

**Comment by aledeniz** [comment]
[This is](https://github.com/aledeniz/camelot-flutter/commit/5af079ef51a93ea27223e5fbf020c9b544c8168c/checks?check_suite_id=312438739) the outcome:

image

**Comment by aledeniz** [comment]
Also, please note it is likely we'll eventually end up doing:

```
jobs:
  integrate-android:
    name: Integrate Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - ...

  integrate-ios:
    name: Integrate iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - ...
```

**Comment by aledeniz** [comment]
@emanuelconunaemme it may also be possible to do something like (pseudo):

```
- name: Building apk
      if:  startsWith(${{ matrix.os }}, 'ubuntu')
      working-directory: ./rousseau_vote
      run: flutter build apk
- name: Building ios
      if:  startsWith(${{ matrix.os }}, 'macos')
      working-directory: ./rousseau_vote
      run: flutter build ios
```

I will give it a try and let you know.

**Review by emanuelconunaemme — APPROVED** [review]
Thank so much. That's a really commit appreciated!

**Pull request merged**
