### PR TITLE
Coverage with CodeCov

### PR DESCRIPTION
**Pull request by aledeniz**
@emanuelconunaemme please note at this point in time I am not requesting for this PR to be approved.
It is just to show you in 96662bf the code (commented out!) which should be enough to integrate with the CodeCov service (plus the deployment of the secret).

P.S.: it is on a branch from #63, if you pull the alternative #65, I'd have to rebase this on top of the latter.

### CODE REVIEW

**Comment by aledeniz** [comment]
I have another branch in my fork where I have actually activated the action, but by the look of it, it requires more commits to start producing reports. I'll keep you posted.

image

**Comment by emanuelconunaemme** [comment]
Ok @aledeniz . Should I just reject it?

**Comment by aledeniz** [comment]
@emanuelconunaemme I will try to merge a few commits on that branch in my fork, and I will let you know the outcome.

**Comment by aledeniz** [comment]
Oh, I got it. Because the builds are now failing on linting, this cannot really be exercised, as coverage is performed with testing, in the next step.
So first we have to pass linting, then we can evaluate code coverage :)

**Pull request closed without merging**
