### PR TITLE
Screen Login user

### PR DESCRIPTION
**Pull request by marcodadamo**
The sign-in screen design code.
I modified some graphics themes, inserting construction content, taking as a reference the vote.rousseau link:
1. Enter your email address
2. Enter your password
3. Check and memeorize my login information
4. Subscribe button
5. Sign in button
6. Bottom left prints M5S logo
7. Link you forgot your password

### CODE REVIEW

**Review by emanuelconunaemme — CHANGES_REQUESTED** [review]
The MaterialApp is created in the main. This should only be the screen. You should just override the build method with your widget. Did you run it?

**Comment by emanuelconunaemme** [comment]
You need to test it first and make sure it runs on a device or on a emulator. Does this run? Plus, with UI commits it would be nice to have a screenshot. I can add this to the guidelines.

**Comment by marcodadamo** [comment]
Questa è il design aggiornato della schermata di accesso utente
Logo Rousseau con sfondo rosso contorno arrotondato.
Inserimento dati (email, password), sfondo bianco, in fondo due pulsanti (accedi, registrati) al lado destro il logo M5S

**Comment by emanuelconunaemme** [comment]
I cannot see the screenshot (404 not found)

**Pull request closed without merging**
